name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git clone -b apk https://github.com/apoorva-raj/test.git
          git checkout --orphan temporary
          echo "Nilee" > newFile.txt
          git add newFile.txt
          git commit -m "gen"
          git -D apk
          git -m apk
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           branch: apk
          
  
