name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v2
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git branch apk
          git checkout apk
          git status
          echo "Nile" > newFile.txt
          git add .
          git commit -m "generated apk"
          git push
