name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download repository
      uses: actions/checkout@v2
    
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Test
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git checkout master
        git add .
        git commit -m "generated"
        git push
