name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git clone --quiet --branch=apk https://github.com/apoorva-raj/test.git apk
          cd apk
          git checkout --orphan temporary
          date > newFile1.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add newFile1.txt
          git status
          git commit -m "gen"
          git branch -D apk
          git push origin --delete apk
          git branch -m apk
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
          
  
