name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git switch --orphan temp
          git push origin --delete apk
          date > newFile1.txt
          git branch -m apk
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add newFile1.txt
          git commit -m "gen"
          git push -u origin apk

          
  
