name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git branch -a
          git checkout main
          git branch -d apk
          git branch apk
          git checkout apk
          echo "Nilee" > newFile.txt
          git add newFile.txt
          git commit -m "gen"
          git push -u origin apk
          
  
