name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - development

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v2
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout main
          git branch -d apk
          git branch apk
          echo "Nile3" > newFile.txt
          git add newFile.txt
          git commit -m "generated apk"
          git push -u origin apk
